function conved_img = patch_conv(img, PSF_cell_path, PSF_h_num, ...
                                 PSF_w_num, patch_length, PSF_uniform_size)
% initializing
conved_img = zeros(size(img));
% pad the input image with the PSF_uniform_size 
% which is the largest size of PSF 
img_pad = padarray(img, [PSF_uniform_size, PSF_uniform_size], 'replicate', 'both');
for PSF_index_h = 1:PSF_h_num
    for PSF_index_w = 1:PSF_w_num
        pad_img_h_range = (PSF_index_h-1)*patch_length+1 : ...
                          (PSF_index_h)*patch_length+2*PSF_uniform_size;
        pad_img_w_range = (PSF_index_w-1)*patch_length+1 : ...
                          (PSF_index_w)*patch_length+2*PSF_uniform_size;
        img_pad_patch = img_pad(pad_img_h_range, pad_img_w_range, :);
        % acquire the corresponding PSF
        PSF_path = strcat(PSF_cell_path, 'PSF_cell_', ...
                          num2str(PSF_index_h, '%03d'), '_', ...
                          num2str(PSF_index_w, '%03d'), '.mat');
        PSF = load(PSF_path);
        PSF = PSF.PSF_info;
        % convolution
        conved_img_pad_patch_r = imfilter(img_pad_patch(:, :, 1), PSF(:, :, 1),...
                                      'conv', 'same', 'replicate');
        conved_img_pad_patch_g = imfilter(img_pad_patch(:, :, 2), PSF(:, :, 2),...
                                      'conv', 'same', 'replicate');
        conved_img_pad_patch_b = imfilter(img_pad_patch(:, :, 3), PSF(:, :, 3),...
                                      'conv', 'same', 'replicate');
        conved_img_pad_patch = cat(3, conved_img_pad_patch_r, ...
                                      conved_img_pad_patch_g, ...
                                      conved_img_pad_patch_b);
        % patch back to the conved_img
        img_h_range = (PSF_index_h-1)*patch_length+1 : ...
                      (PSF_index_h)*patch_length;
        img_w_range = (PSF_index_w-1)*patch_length+1 : ...
                      (PSF_index_w)*patch_length;
        conved_img(img_h_range, img_w_range, :) = ...
            conved_img_pad_patch(PSF_uniform_size+1 : PSF_uniform_size+patch_length, ...
                                 PSF_uniform_size+1 : PSF_uniform_size+patch_length, :);
    end
end
end

